### ISSUE TITLE
1.0 Tareas iniciales

### ISSUE THREAD

**Issue by ValeriaRoberts** [David-Damian/Optimization-Delaunay-surfaces#2]
La tarea inicial consiste en crear el README y en él, detallar de forma general la estructura del proyecto y del repositorio.

**Comment by ValeriaRoberts** [comment]
Además organizar los Issues y los Milestones para tener un camino claro del desarollo del proyecto

**Comment by David-Damian** [comment]
Hola @ValeriaRoberts ! Noté que se añadierpon los roles en el README del directorio `avance1` pero faltó actualizarlos en el README del repo en general. :)

**Comment by ValeriaRoberts** [comment]
Hola @David-Damian, muchas gracias por tu observación. En un rato los actualizo.

**Comment by ValeriaRoberts** [comment]
Queda pendiente realizar el primer pull request
