### ISSUE TITLE
3.0 Programación del método Runge Kutta

### ISSUE THREAD

**Issue by ValeriaRoberts** [David-Damian/Optimization-Delaunay-surfaces#4]
Programen y solución del problema.  (esto para un equipo de 2 personas)

**Comment by JuanPalms** [comment]
subi una primer version del metodo pero estoy teniendo problemas con los indices. puedes revisarlo @David-Damian ?

**Comment by David-Damian** [comment]
Claro. Lo reviso más tarde hoy👌🏻

**Comment by David-Damian** [comment]
Listo @JuanPalms , ya quedó!

**Comment by ValeriaRoberts** [comment]
Buen trabajo equipo!
