### ISSUE TITLE
5.0 Reporte

### ISSUE THREAD

**Issue by ValeriaRoberts** [David-Damian/Optimization-Delaunay-surfaces#6]

**Comment by JuanPalms** [comment]
Val @ValeriaRoberts, para el reporte entendí que debemos generar una liga hacia un drive o dropbox. 

Sugiero que el noteboook que subiste con nuestro primer avance del reporte lo conviertas a pdf. Después lo subas a tu cuenta de Drive por ejemplo y anexes la liga al README del repo hacia éste documento. Especififcamente ví que en el README pricnipal hay un apartado llamado `Trabajo escrito`

**Comment by ValeriaRoberts** [comment]
Muchas gracias @JuanPalms por tu observación. He añadido el link correspondiente. Solo dejare pendiente su revisión y bajar el notebook que tenemos.

**Comment by ValeriaRoberts** [comment]
Listo! Se ha revisado el link y además se borro el notebook del reporte.
