### ISSUE TITLE
3.1 Programación para resolver el problema

### ISSUE THREAD

**Issue by ValeriaRoberts** [David-Damian/Optimization-Delaunay-surfaces#8]

**Comment by David-Damian** [comment]
esta tarea fue concluida desde hace varios días :)

**Comment by ValeriaRoberts** [comment]
Dado que faltaba la programación de las gráficas de las superficies, el issue continuaba abierto. Pero se ha cumplido con esta tarea exitosamente y ahora se puede cerrar. Buen trabajo!
